function toggleMenu(){var menu=document.getElementById('mobile-menu');menu.classList.toggle('active');var icon=document.querySelector('.hamburger-btn i');if(menu.classList.contains('active')){icon.classList.remove('fa-bars');icon.classList.add('fa-xmark')}else{icon.classList.remove('fa-xmark');icon.classList.add('fa-bars')}}
document.addEventListener("DOMContentLoaded",function(){var socialLinks=document.querySelectorAll('.social-link');socialLinks.forEach(function(link){var text=link.innerText.trim().toLowerCase();if(text.startsWith('#')){var iconName=text.substring(1);link.innerText='';var i=document.createElement('i');if(iconName==='facebook')i.className='fa-brands fa-facebook-f';else if(iconName==='instagram')i.className='fa-brands fa-instagram';else if(iconName==='tiktok')i.className='fa-brands fa-tiktok';else if(iconName==='whatsapp')i.className='fa-brands fa-whatsapp';else if(iconName==='twitter'||iconName==='x')i.className='fa-brands fa-x-twitter';else if(iconName==='youtube')i.className='fa-brands fa-youtube';else i.className='fa-solid fa-link';link.appendChild(i)}})});document.addEventListener("DOMContentLoaded",function(){const slides=document.querySelectorAll('.hero-slide');if(slides.length>0){let currentSlide=0;slides[0].classList.add('active');window.changeSlide=function(direction){slides[currentSlide].classList.remove('active');currentSlide+=direction;if(currentSlide>=slides.length){currentSlide=0}
if(currentSlide<0){currentSlide=slides.length-1}
slides[currentSlide].classList.add('active')};setInterval(function(){changeSlide(1)},5000)}});window.onload=function(){var devID="motawir-dzair";var devUrl="https://motawir-dzair.blogspot.com/";var el=document.getElementById(devID);function redirectToDev(){document.body.innerHTML="";document.body.style.backgroundColor="#fff";var box=document.createElement("div");box.style.cssText="position:fixed; top:50%; left:50%; transform:translate(-50%, -50%); text-align:center; font-family:sans-serif; background:#f8d7da; color:#721c24; padding:30px; border:1px solid #f5c6cb; border-radius:10px; box-shadow:0 0 20px rgba(0,0,0,0.1); z-index:999999;";box.innerHTML="<h1>⚠️ تنبيه حقوق الملكية</h1><p>تم اكتشاف تلاعب في حقوق تصميم القالب.</p><p>هذا القالب من تصميم <b>مطور دزاير</b>، ولا يمكن إزالة الحقوق.</p><a href='"+devUrl+"' style='background:#721c24; color:#fff; padding:10px 20px; text-decoration:none; border-radius:5px; display:inline-block; margin-top:15px;'>زيارة موقع المطور</a>";document.body.appendChild(box);setTimeout(function(){window.location.href=devUrl},4000)}
if(el==null){redirectToDev()}else{if(el.href!==devUrl){redirectToDev()}
if(el.style.display==="none"||el.style.visibility==="hidden"||el.style.opacity==="0"){redirectToDev()}
if(el.innerHTML.trim()!=="مطور دزاير"){}}
setInterval(function(){var elCheck=document.getElementById(devID);if(!elCheck||elCheck.href!==devUrl||elCheck.style.display==="none"){redirectToDev()}},2000)};document.addEventListener("DOMContentLoaded",function(){const targets=document.querySelectorAll('.product-description img, .product-description video, .product-description iframe');const observer=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{root:null,threshold:0.10,rootMargin:"0px 0px -50px 0px"});targets.forEach(el=>{el.classList.add('reveal-element');observer.observe(el)})});document.addEventListener("DOMContentLoaded",function(){if(typeof window.mySalesData==='undefined'||window.mySalesData.length===0){return}
const box=document.getElementById('sp-notification');const delayBetween=10000;const showTime=5000;function showRandomSale(){const item=window.mySalesData[Math.floor(Math.random()*window.mySalesData.length)];const times=['الآن','منذ دقيقة','منذ 2 دقيقة','منذ 5 دقائق','منذ 12 دقيقة'];const randomTime=times[Math.floor(Math.random()*times.length)];document.getElementById('sp-name').innerText=item.name;document.getElementById('sp-city').innerText=item.city;document.getElementById('sp-product').innerText=item.product;document.getElementById('sp-time').innerText=randomTime;box.classList.add('show');setTimeout(()=>{box.classList.remove('show')},showTime)}
setInterval(()=>{if(!box.classList.contains('show')){showRandomSale()}},delayBetween+showTime);setTimeout(showRandomSale,5000)});function closeOfferBar(){document.getElementById('offer-bar').style.display='none';document.body.style.paddingBottom='0'}
document.addEventListener("DOMContentLoaded",function(){if(typeof window.offerConfig==='undefined')return;const bar=document.getElementById('offer-bar');const msgElement=document.getElementById('cnt-message');const countDownDate=new Date(window.offerConfig.date).getTime();if(window.offerConfig.text)msgElement.innerText=window.offerConfig.text;const x=setInterval(function(){const now=new Date().getTime();const distance=countDownDate-now;const days=Math.floor(distance/(1000*60*60*24));const hours=Math.floor((distance%(1000*60*60*24))/(1000*60*60));const minutes=Math.floor((distance%(1000*60*60))/(1000*60));const seconds=Math.floor((distance%(1000*60))/1000);document.getElementById("days").innerText=days<10?"0"+days:days;document.getElementById("hours").innerText=hours<10?"0"+hours:hours;document.getElementById("minutes").innerText=minutes<10?"0"+minutes:minutes;document.getElementById("seconds").innerText=seconds<10?"0"+seconds:seconds;bar.style.display="block";if(bar.offsetHeight>0){document.body.style.paddingBottom=bar.offsetHeight+"px"}
if(distance<0){clearInterval(x);closeOfferBar()}},1000)})
